name: pytest

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install pytest
        run: python -m pip install pytest
      - name: Update apt
        run: sudo apt-get update
      - name: Install COIN
        run: sudo apt-get install coinor-libcbc-dev
      - name: Install numpy
        run: python -m pip install numpy
      - name: Install requirements
        run: python -m pip install -r requirements.txt
      - name: Install cylp
        run: python -m pip install cylp
      - name: Run pytest
        run: python -m pytest
